sudo: required
dist: trusty
group: deprecated-2017Q4
services:
  - docker

env:
  global:
    - DOCKER_DATA=/tmp/data
    - DOCKER_COMPOSE_VERSION=1.13.0
    - secure: B2o+OVhyzRFr0SvLl18FtTT6DO6+d69BizgULki5MTgMdxGJrVAEoj+AAl5edwJwjN6MZ4OiSCLoauKHjjlHjZT2A0J8wMHGCAD3IpdpZ9wacw0qjkNKkUXDRTdFycDXVTngHn0YJ++tA7kHG98DAkRq7YfWrsb5kxxFo54Gl8UkvWpOxKx0nd6n1d4/OooKYhSXaPKPcZ/Mpa/LR1/O2xC61RBYrzk3DPlFmW5+4F2iSKh7ALPd92joyDsxRnOuVcQU/aCb6fUPwVH7znn2Rw9i8pwCYNXoJdNzM0DvyV4tFf1aigsHS7uGRFtzXGSe57MEoJl7prCbHKjHLZ+ZrOgay4CmYmpdEAYKTJwNPdM1mm80wftYfyo3kMynDoJU82wvGwlQ4ZDYckvJ11XVKASLO40QNxLiZaOCs++R4WExVbK2yNGMUyoC26Z7pJl2t5FGEdBjr73Ee19NslwFgGBsI5IE1JG7SToFFVaQiwIKuuTEQX81JZFsihpv8SgaAFj2Ur6D50yh4YnUbau7f2wei6xHlKg+GGYQsMweYxXQUrAzdr5igOrb3AJ3dW8h9vH6LIERlblImbvAFu0xFl0dK1Bbv6TkB908DVtN1JzrcN1iu9ca6cXyIfuSkR8cBQ/DK3Ih8s/V1slq1Qf71ydt1a+TVT95rtq1StnneD0=
    - secure: TPae1TtBCdNxaZprJ6H1gsyyznJ+JSKqAJOz/b4GatG4+yru2JWjc6HSXWMQ6MGQtyyxJpq5PRlnNH9HFRc7OSe4KgmDd8CkwJBXFV8qK1cRXKgiG7X75gIcRx4RCLw5z2VcmNc2cdq7Zh4y/1q1kmRrlqMqEF/c8/k/+naenffy6W6bqbL0rWfGmyQJ6YaxZCUuqfWVPzAbwR81tAhIuSj5I9/eKKjpmtc5Z/yZ990zl7zFz8j4Fn96Vv+qeDwumLHlK9DP9t1I13IW05jZY1TRnCSw0qRTpdXdEM0Cdzhmb9rBe10MikkHhhEkmxlv6gNSkDdupJniUi7ETdWUrfq6rzDRGBrCpce273aq2mykH8+Cqb76L6iD20nbPNm01/W65Td/E51XrYK4gSa9ZgBDddpoG4vk0kiZq96N3a/vLf4c8e7zwOxT2HIk2SECgan2pGbs5wCrUN5g+hdLaDVn8XqZdlFPfs5FKL8Yu9tNlarFWz9aqpRwvDZc3u8ikIFukCgouQZvcd5srH69ZCZB8kV5TUWWBO2UZVKv5K+7Ym+5HdLNYdUsA0fCVxIS+0u6UqT7w7JWkCANXICubAfEqpNB68CKrxMjSAlzxoBxpWlS+Wu0NLfoHQYw8m1xdrHax2hCIYsEXvmuAi7Z8qtNdWBn8XK9wcEQaLFdGVo=
    - secure: sI+rBt9WC8ag/iL3ul6Onz8mQhj9UDjqLGqOXowN3fg5ElCm7wI6gXEaFhAt+LABL9Fu62YTr8U5OZkkj2EoVvyzKQBMcV89g460CJh077dNVrmbM2Ot3vMm0iMnsGtRHA4rODLFicdUKVinKP8tJfrw3BWCGA20+ZI10oD8JOeqiMSu3hjYrS8uNMdkcvRV6xKWa5ABr/fDbLo9ErcHKSKavpUPD+3G+WKsW6BdGC8IhA5qwLYWDQeUZez/Yi2ry2clgGloW1GhYf/h+LAdxOw9lDTs+AmRlWmQgv7bszF5vbnKXHXnAVPxvk+VC9v06XLR8PpFjQCJwrU52wZFTjxvOXw/vgyrMcEWQiDQmPbSo1cBI5cE6E4TAvcvwbUlvCBuBMg44SSoBecj7WsnigzRdUQh5m4UeFOpR548yRjsckwONcT6DZah01lLKdcziyOLy28SPxbfnyoV3A0CMfobrPijfYF55hFMkdz8wD4As0IYS+OcFe9nLEcCWQYTClaUqFsdX62oFkUoDRvR0F+pYH/HTttt8LscXaxjUn+KQtLmcANEVf28vnR1foT2WNCyIK9zV3Hepd/2w0Xi88kCM/sTPEu7ON/3BfD4Gv6vu3a3nSthHwUIacQGn4LsPegVKG6Mymc4bj7YQCZjPO9L+qxqZ3zSWpg5ziXQvVc=

matrix:
  include:
  - env:
    - DOCKER_PROJECT=inspirehep/python-base
    - DOCKER_IMAGE_TAG=2.7
    - DOCKERFILE=python_base/Dockerfile
    - ARGS='--build-arg=INSPIRE_PYTHON_VERSION=2.7'
  - env:
    - DOCKER_PROJECT=inspirehep/python-base
    - DOCKER_IMAGE_TAG=latest
    - DOCKERFILE=python_base/Dockerfile
    - ARGS='--build-arg=INSPIRE_PYTHON_VERSION=2.7'
  - env:
    - DOCKER_PROJECT=inspirehep/elasticsearch
    - DOCKER_IMAGE_TAG=latest
    - DOCKERFILE=elasticsearch/Dockerfile
    - ARGS=''

script:
  - chmod +x *.sh
  - ./build.sh && ./test.sh -v && ./deploy.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/71f1c347013ea34197ee
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    - inspire-adimn@cern.ch
